using Dalamud.Configuration;
using Dalamud.Plugin;
using System;

namespace Resonance;

[Serializable]
public class Configuration : IPluginConfiguration
{
    public int Version { get; set; } = 1;

    // Legacy manual setup (for advanced users)
    public string AtProtocolHandle { get; set; } = string.Empty;
    public string AtProtocolPassword { get; set; } = string.Empty;
    
    // New auto-account system
    public string ResonanceHandle { get; set; } = string.Empty; // User's chosen display name
    public string AutoGeneratedHandle { get; set; } = string.Empty; // Generated ffxiv-sync-xxx.bsky.social
    public string AutoGeneratedPassword { get; set; } = string.Empty; // Generated password
    public bool UseAutoAccount { get; set; } = true; // Default to auto-account
    
    public bool IsConfigured { get; set; } = false;
    public bool ShowSetupWindow { get; set; } = true;
    public bool ShowWelcomeMessage { get; set; } = true;
    
    public bool IsConfigWindowMovable { get; set; } = true;
    public bool EnableDebugLogging { get; set; } = false;

    [NonSerialized]
    private IDalamudPluginInterface? _pluginInterface;

    public void Initialize(IDalamudPluginInterface pluginInterface)
    {
        _pluginInterface = pluginInterface;
    }

    public void Save()
    {
        _pluginInterface?.SavePluginConfig(this);
    }
}